/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface GlobalStats {
  'countriesActive' : bigint,
  'totalCreditsIssued' : bigint,
  'projectsVerified' : bigint,
  'totalLandRestored' : PositiveFloat,
}
export type PositiveFloat = number;
export interface Project {
  'id' : bigint,
  'status' : ProjectStatus,
  'country' : string,
  'endDate' : string,
  'ownerName' : string,
  'projectType' : string,
  'gpsCoordinates' : string,
  'createdAt' : bigint,
  'landAreaHectares' : PositiveFloat,
  'creditsPurchased' : bigint,
  'creditsRequired' : bigint,
  'startDate' : string,
}
export type ProjectId = bigint;
export type ProjectStatus = { 'verified' : null } |
  { 'pending' : null } |
  { 'rejected' : null } |
  { 'inProgress' : null };
export interface RestorationSubmission {
  'id' : bigint,
  'files' : Array<ExternalBlob>,
  'status' : SubmissionStatus,
  'completionDate' : string,
  'submittedAt' : bigint,
  'description' : string,
  'reviewerNote' : string,
  'projectId' : bigint,
}
export type SubmissionId = bigint;
export type SubmissionStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'approveRestoration' : ActorMethod<[SubmissionId], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAdminSubmissions' : ActorMethod<[], Array<RestorationSubmission>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getGlobalStats' : ActorMethod<[], GlobalStats>,
  'getGreenMap' : ActorMethod<[], Array<Project>>,
  'getProject' : ActorMethod<[ProjectId], [] | [Project]>,
  'getProjects' : ActorMethod<[], Array<Project>>,
  'getRestorationSubmissions' : ActorMethod<[], Array<RestorationSubmission>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'purchaseCredits' : ActorMethod<[ProjectId, bigint], boolean>,
  'rejectRestoration' : ActorMethod<[SubmissionId, string], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitProject' : ActorMethod<
    [string, string, string, PositiveFloat, string, string, string],
    ProjectId
  >,
  'submitRestoration' : ActorMethod<
    [ProjectId, string, string, Array<ExternalBlob>],
    SubmissionId
  >,
  'updateProjectStatus' : ActorMethod<[ProjectId, ProjectStatus], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];