/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const SubmissionId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const SubmissionStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const RestorationSubmission = IDL.Record({
  'id' : IDL.Nat,
  'files' : IDL.Vec(ExternalBlob),
  'status' : SubmissionStatus,
  'completionDate' : IDL.Text,
  'submittedAt' : IDL.Int,
  'description' : IDL.Text,
  'reviewerNote' : IDL.Text,
  'projectId' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const PositiveFloat = IDL.Float64;
export const GlobalStats = IDL.Record({
  'countriesActive' : IDL.Nat,
  'totalCreditsIssued' : IDL.Nat,
  'projectsVerified' : IDL.Nat,
  'totalLandRestored' : PositiveFloat,
});
export const ProjectStatus = IDL.Variant({
  'verified' : IDL.Null,
  'pending' : IDL.Null,
  'rejected' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const Project = IDL.Record({
  'id' : IDL.Nat,
  'status' : ProjectStatus,
  'country' : IDL.Text,
  'endDate' : IDL.Text,
  'ownerName' : IDL.Text,
  'projectType' : IDL.Text,
  'gpsCoordinates' : IDL.Text,
  'createdAt' : IDL.Int,
  'landAreaHectares' : PositiveFloat,
  'creditsPurchased' : IDL.Nat,
  'creditsRequired' : IDL.Nat,
  'startDate' : IDL.Text,
});
export const ProjectId = IDL.Nat;

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'approveRestoration' : IDL.Func([SubmissionId], [IDL.Bool], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAdminSubmissions' : IDL.Func(
      [],
      [IDL.Vec(RestorationSubmission)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGlobalStats' : IDL.Func([], [GlobalStats], ['query']),
  'getGreenMap' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getProject' : IDL.Func([ProjectId], [IDL.Opt(Project)], ['query']),
  'getProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getRestorationSubmissions' : IDL.Func(
      [],
      [IDL.Vec(RestorationSubmission)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'purchaseCredits' : IDL.Func([ProjectId, IDL.Nat], [IDL.Bool], []),
  'rejectRestoration' : IDL.Func([SubmissionId, IDL.Text], [IDL.Bool], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitProject' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        PositiveFloat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [ProjectId],
      [],
    ),
  'submitRestoration' : IDL.Func(
      [ProjectId, IDL.Text, IDL.Text, IDL.Vec(ExternalBlob)],
      [SubmissionId],
      [],
    ),
  'updateProjectStatus' : IDL.Func([ProjectId, ProjectStatus], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const SubmissionId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const SubmissionStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const RestorationSubmission = IDL.Record({
    'id' : IDL.Nat,
    'files' : IDL.Vec(ExternalBlob),
    'status' : SubmissionStatus,
    'completionDate' : IDL.Text,
    'submittedAt' : IDL.Int,
    'description' : IDL.Text,
    'reviewerNote' : IDL.Text,
    'projectId' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const PositiveFloat = IDL.Float64;
  const GlobalStats = IDL.Record({
    'countriesActive' : IDL.Nat,
    'totalCreditsIssued' : IDL.Nat,
    'projectsVerified' : IDL.Nat,
    'totalLandRestored' : PositiveFloat,
  });
  const ProjectStatus = IDL.Variant({
    'verified' : IDL.Null,
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const Project = IDL.Record({
    'id' : IDL.Nat,
    'status' : ProjectStatus,
    'country' : IDL.Text,
    'endDate' : IDL.Text,
    'ownerName' : IDL.Text,
    'projectType' : IDL.Text,
    'gpsCoordinates' : IDL.Text,
    'createdAt' : IDL.Int,
    'landAreaHectares' : PositiveFloat,
    'creditsPurchased' : IDL.Nat,
    'creditsRequired' : IDL.Nat,
    'startDate' : IDL.Text,
  });
  const ProjectId = IDL.Nat;
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'approveRestoration' : IDL.Func([SubmissionId], [IDL.Bool], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAdminSubmissions' : IDL.Func(
        [],
        [IDL.Vec(RestorationSubmission)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGlobalStats' : IDL.Func([], [GlobalStats], ['query']),
    'getGreenMap' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getProject' : IDL.Func([ProjectId], [IDL.Opt(Project)], ['query']),
    'getProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getRestorationSubmissions' : IDL.Func(
        [],
        [IDL.Vec(RestorationSubmission)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'purchaseCredits' : IDL.Func([ProjectId, IDL.Nat], [IDL.Bool], []),
    'rejectRestoration' : IDL.Func([SubmissionId, IDL.Text], [IDL.Bool], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitProject' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          PositiveFloat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [ProjectId],
        [],
      ),
    'submitRestoration' : IDL.Func(
        [ProjectId, IDL.Text, IDL.Text, IDL.Vec(ExternalBlob)],
        [SubmissionId],
        [],
      ),
    'updateProjectStatus' : IDL.Func(
        [ProjectId, ProjectStatus],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };